log:
  applicants:
    file: logs/applicants_log.csv
  jobs:
    file: logs/jobs_log.csv
  cover_letters:
    file: logs/cover_letters_log.csv
  applications:
    file: logs/applications_log.csv
database:
  sqlite:
    path: sqlite:///logs/database.db
resume:
  template:
    file: examples/resume_template.docx
cover_letter:
  template:
    file: examples/cover_letter_template.docx
applicant:
  first_name: Ivan
  last_name: Kaliuzhnyi
  contacts:
    email: i.kaliuzhnyi.ca@gmail.com
    phone: +1 (437) 441-6585
    address: &applicant_address Barrie, ON
  resume:
    file: tests/Resume.IvanKaliuzhnyi.pdf
  cover_letter:
    file:
job:
  title: java developer
  location: *applicant_address
openai:
  version: gpt-4o-mini
  create_applicant_email:
    developer_content: |
      You are a professional employment consultants. Your goal is to get me a job.
      Generate the professional body text for an email for a job application, excluding the subject line or other elements. The email should include the following:
      1. A polite greeting - Dear Hiring Manager.
      2. A brief introduction, mentioning the applicant's name and the position they are applying for. When indicating work experience, do not use exact values. Personalize your experience and skills to meet the needs of the vacancy.
      3. A statement about attaching the resume and cover letter.
      4. A short sentence expressing interest in the company and the role.
      5. A thank you note and a closing statement.
      Ensure the email is fully polished, complete, and ready for immediate use without requiring any edits or additional input.
      Instead, use appropriate wording to make the email universally applicable and professional.
      DO NOT INCLUDE ANY PLACEHOLDERS OR GENERIC TERM!!!
      The output must be formatted and ready to send directly.
    user_content: &user_content |
      Company: {job.business}
      Position: {job.title}
      Job details: {job.description}
      Applicant name: {applicant.first_name} {applicant.last_name}
      Applicant contacts: {applicant.email}, {applicant.phone}, {applicant.address}
  create_applicant_cover_letter:
    developer_content: |
      You are a professional employment consultants. Your goal is to get me a job.
      Generate the professional cover letter for a job application, excluding the subject line or other elements. The cover letter should include the following:
      1. A polite greeting - Dear Hiring Manager.
      2. A brief introduction, mentioning the applicant's name and the position they are applying for. When indicating work experience, do not use exact values. Personalize your experience and skills to meet the needs of the vacancy.
      3. A statement about attaching the resume and cover letter.
      4. A short sentence expressing interest in the company and the role.
      5. A thank you note and a closing statement.
      Ensure the cover letter is fully polished, complete, and ready for immediate use without requiring any edits or additional input.
      Instead additional inputs, use appropriate wording to make the email universally applicable and professional.
      DO NOT INCLUDE ANY PLACEHOLDERS OR GENERIC TERM!!!
    user_content: *user_content