# Logging configuration
# Use this section to define files for logging different operations.
# To disable logging for a particular section, leave the corresponding 'file' field empty.
log:
  applicants:
    file: logs/applicants_log.csv # Leave this field blank to disable applicant logs.
  jobs:
    file: logs/jobs_log.csv # Leave this blank if you do not need job logging.
  resumes:
    file: logs/resumes_log.csv # Disable resume logging by leaving this field blank.
  cover_letters:
    file: logs/cover_letters_log.csv # Leave this field blank to deactivate logging.
  applications:
    file: logs/applications_log.csv # Leave it empty to disable logging for applications.
database:
  path: sqlite:///logs/database.db # To disable logging in database - leave this field blank
resume:
  template:
    file: examples/resume_template.docx
cover_letter:
  template:
    file: examples/cover_letter_template.docx
applicant:
  first_name: Ivan
  last_name: Ivanov
  contacts:
    email: i.ivanov@gmail.com
    phone: +1 (437) 865-4215
    address: &applicant_address Toronto, ON
  resume:
    file: # If field is empty, AI will generate text and file
  cover_letter:
    file: # If field is empty, AI will generate text and file
  summary:
  skills:
    - •  Execution of full accounting cycle, including AP/AR, payroll, and tax remittances.
    - •  Preparation and analysis of financial statements (assets, liabilities, equity, income statements).
    - •  Strong knowledge of Canadian accounting principles and practices.
    - •  Proficient in QuickBooks, enterprise accounting software, and financial data integration.
    - •  Skilled in reconciliation processes for accounts and bank statements.
    - •  Advanced Excel skills, including pivot tables, VLOOKUP, and macros.
    - •  Excellent attention to detail and organizational skills.
    - •  Critical thinking and problem-solving abilities.
    - •  Strong communication skills, both written and verbal.
  education:
    # Education 1
    - title: •  Bookkeeping
      organization: Lilico Accounting Corporation
      date:
        start: 2025
        end: 2025
      description:
    # Education 2
    - title: •  Intuit Academy Bookkeeping
      organization: INTUIT
      date:
        start: 2024
        end: 2024
      description: |
        Completed the Intuit Academy Bookkeeping program, gaining a strong foundation in bookkeeping principles, financial statements, and accounting measurement.
        Developed skills in the double-entry bookkeeping system, bank reconciliations, and financial statement analysis.
        Acquired hands-on experience with QuickBooks Online and real-world accounting scenarios.
  experience:
    # Experience/job 1
    - title: Bookkeeper
      company: ABC Accounting Services
      date:
        start: Jan 2023
        end: Present
      description: |
        ．Managed full-cycle bookkeeping, including accounts payable, accounts receivable, payroll, and reconciliations, ensuring financial accuracy and compliance with regulations.
        ．Prepared financial statements, balance sheets, and income statements to provide management with a clear overview of the company’s financial health.
        ．Processed invoices, payments, and expense reports, maintaining accurate and up-to-date financial records.
        ．Ensured compliance with Canadian tax laws, filing GST/HST returns and assisting with corporate tax preparations.
        ．Utilized QuickBooks and other accounting software to track transactions, generate reports, and improve efficiency in financial management.
        ．Collaborated with external auditors and tax advisors to ensure accurate reporting and regulatory compliance.
        ．Implemented process improvements to streamline financial workflows and reduce manual data entry errors.
    # Experience/job 2
    - title: Bookkeeper
      company: XYZ Consulting Group
      date:
        start: Jun 2021
        end: Dec 2022
      description: |
        ．Maintained financial records, processed transactions, and performed monthly bank reconciliations to ensure accurate bookkeeping.
        ．Assisted in the preparation of financial reports, budgets, and forecasts, supporting management in strategic decision-making.
        ．Managed payroll processing, ensuring timely salary payments and compliance with employment regulations.
        ．Handled accounts payable and receivable, tracking due payments and following up on outstanding invoices.
        ．Prepared year-end financial statements and coordinated with accountants for tax filing and audits.
        ．Implemented bookkeeping best practices, improving financial reporting accuracy and operational efficiency.
    # Experience/job 3
    - title: Junior Bookkeeper
      company: LMN Business Solutions
      date:
        start: Jan 2020
        end: May 2021
      description: |
        ．Recorded financial transactions, reconciled bank statements, and maintained ledgers for accurate bookkeeping.
        ．Assisted with payroll processing and tax calculations, ensuring compliance with local regulations.
        ．Prepared financial summaries and assisted senior accountants in compiling reports for management.
        ．Processed invoices, receipts, and payments, keeping financial records up to date.
        ．Worked with QuickBooks and Excel to manage financial data and generate reports.
        ．Supported the finance team in budgeting and expense tracking, improving financial organization and planning.
job:
  title: bookkeeper
  location: Toronto, ON # if looking for jobs in city where applicant live use anchor - *applicant_address
  applying: true # if false jobs are only finding and save, otherwise jobs will be applied as well
openai:
  version: gpt-4o-mini
  create_applicant_email:
    developer_content: |
      You are a professional employment consultants. Your goal is to get me a job.
      Generate the professional body text for an email for a job application, excluding the subject line or other elements. The email should include the following:
      1. A polite greeting - Dear Hiring Manager.
      2. A brief introduction, mentioning the applicant's name and the position they are applying for. When indicating work experience, do not use exact values. Personalize your experience and skills to meet the needs of the vacancy.
      3. A statement about attaching the resume and cover letter.
      4. A short sentence expressing interest in the company and the role.
      5. A thank you note and a closing statement.
      Ensure the email is fully polished, complete, and ready for immediate use without requiring any edits or additional input.
      Instead, use appropriate wording to make the email universally applicable and professional.
      DO NOT INCLUDE ANY PLACEHOLDERS OR GENERIC TERM!!!
      The output must be formatted and ready to send directly.
    user_content: &user_content |
      Company: {job.business}
      Position: {job.title}
      Job details: {job.description}
      Applicant name: {applicant.first_name} {applicant.last_name}
      Applicant contacts: {applicant.email}, {applicant.phone}, {applicant.address}
  create_applicant_cover_letter:
    developer_content: |
      You are a professional employment consultants. Your goal is to get me a job.
      Generate the professional cover letter for a job application, excluding the subject line or other elements. The cover letter should include the following:
      1. A polite greeting - Dear Hiring Manager.
      2. A brief introduction, mentioning the applicant's name and the position they are applying for. When indicating work experience, do not use exact values. Personalize your experience and skills to meet the needs of the vacancy.
      3. A statement about attaching the resume and cover letter.
      4. A short sentence expressing interest in the company and the role.
      5. A thank you note and a closing statement.
      Ensure the cover letter is fully polished, complete, and ready for immediate use without requiring any edits or additional input.
      Instead additional inputs, use appropriate wording to make the email universally applicable and professional.
      DO NOT INCLUDE ANY PLACEHOLDERS OR GENERIC TERM!!!
    user_content: *user_content
  create_applicant_resume:
    developer_content: |
      You are an AI assistant that helps tailor resumes to match specific job postings.
      INPUT DATA:
      You will receive a JSON with two sections:
      1. Candidate Information – includes skills, work experience, and education.
      2. Job Description – includes job requirements, responsibilities, and employer preferences.
      TASK:
      Based on these inputs, generate an optimized JSON resume that aligns with the job description.
      EXPECTATIONS:
      - Rephrase work experience descriptions to emphasize key job requirements.
      - Keep only relevant skills and add missing ones if they logically fit the candidate's background.
      - Restructure responsibilities to match the job posting language.
      - Change skills to emphasize job requirements.
      - Create and/or change summary to emphasize job requirements.
      - Maintain the original JSON structure.
      CONSTRAINTS:
      - Do not invent experience or skills that are not present in the input data.
      - Use professional and natural language.
      OUTPUT FORMAT:
      Return a ONLY JSON with the same structure as the input, but with adjusted data.
      Result should contain only JSON, because this text needed to be parsed.
    user_content: |
      CANDIDATE INFORMATION (JSON):
      {json}
      JOB DESCRIPTION:
        Company: {job.business}
        Position: {job.title}
        Job details: {job.description}
